"""Interactive setup wizard for OpenMem.

Run with:
    openmem-setup              # if installed via pip
    python -m openmem.mcp.setup  # direct invocation

Walks through storage path, embedding provider, and API keys.
Saves configuration to ~/.openmem/config.env.
"""

from __future__ import annotations

import getpass
import json
import os
import stat
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Optional


CONFIG_DIR = Path.home() / ".openmem"
CONFIG_FILE = CONFIG_DIR / "config.env"


# --- Helpers ---


def _ask(prompt: str, default: str = "") -> str:
    """Prompt the user with an optional default value."""
    suffix = f" [{default}]" if default else ""
    value = input(f"  {prompt}{suffix}: ").strip()
    return value if value else default


def _ask_secret(prompt: str, default: str = "") -> str:
    """Prompt for a secret value (hidden input)."""
    suffix = " [****]" if default else ""
    value = getpass.getpass(f"  {prompt}{suffix}: ").strip()
    return value if value else default


def _ask_choice(prompt: str, options: list[str], default: int = 1) -> int:
    """Present a numbered menu and return the chosen index (1-based)."""
    print(f"\n  {prompt}")
    for i, opt in enumerate(options, 1):
        marker = "*" if i == default else " "
        print(f"    {marker} {i}) {opt}")
    while True:
        raw = input(f"  Choose [{default}]: ").strip()
        if not raw:
            return default
        try:
            choice = int(raw)
            if 1 <= choice <= len(options):
                return choice
        except ValueError:
            pass
        print(f"    Please enter a number between 1 and {len(options)}")


def _ask_confirm(prompt: str, default: bool = True) -> bool:
    """Ask a yes/no question."""
    hint = "Y/n" if default else "y/N"
    raw = input(f"  {prompt} [{hint}]: ").strip().lower()
    if not raw:
        return default
    if raw in ("y", "yes"):
        return True
    if raw in ("n", "no"):
        return False
    return default


def _mask_key(key: str) -> str:
    """Mask an API key for display."""
    if len(key) <= 8:
        return "****"
    return key[:8] + "..."


# --- Validation ---


def _validate_openai_embedding(
    api_key: str,
    base_url: str,
    model: str,
    dimensions: Optional[int] = None,
) -> tuple[bool, str]:
    """Test an OpenAI-compatible embedding endpoint.

    Returns (success, message).
    """
    url = f"{base_url.rstrip('/')}/embeddings"
    body: dict = {"input": "hello", "model": model}
    if dimensions is not None:
        body["dimensions"] = dimensions

    data = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read().decode("utf-8"))
        embedding = result["data"][0]["embedding"]
        dims = len(embedding)
        return True, f"Connection successful ({dims}-dimensional embeddings)"
    except urllib.error.HTTPError as e:
        body_text = ""
        try:
            body_text = e.read().decode("utf-8", errors="replace")[:200]
        except Exception:
            pass
        return False, f"HTTP {e.code}: {body_text}"
    except urllib.error.URLError as e:
        return False, f"Connection failed: {e.reason}"
    except Exception as e:
        return False, f"Error: {e}"


def _validate_ollama(base_url: str) -> tuple[bool, str]:
    """Test Ollama connectivity."""
    try:
        req = urllib.request.Request(base_url.rstrip("/"), method="GET")
        with urllib.request.urlopen(req, timeout=5) as resp:
            resp.read()
        return True, "Ollama is running"
    except urllib.error.URLError:
        return False, f"Cannot connect to Ollama at {base_url}"
    except Exception as e:
        return False, f"Error: {e}"


# --- Config file I/O ---


def _load_existing_config() -> dict[str, str]:
    """Load existing config.env if present."""
    config: dict[str, str] = {}
    if not CONFIG_FILE.exists():
        return config
    for line in CONFIG_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        config[key.strip()] = value.strip()
    return config


def _save_config(config: dict[str, str]) -> Path:
    """Save configuration to ~/.openmem/config.env.

    Returns the path to the saved file.
    """
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "# OpenMem configuration",
        "# Generated by openmem-setup",
        "",
    ]
    for key, value in config.items():
        if value:  # skip empty values
            lines.append(f"{key}={value}")
    lines.append("")

    CONFIG_FILE.write_text("\n".join(lines))

    # Restrict permissions — file contains API keys
    try:
        CONFIG_FILE.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 0o600
    except OSError:
        pass  # best effort (may fail on Windows)

    return CONFIG_FILE


# --- Setup flows ---


def _setup_openai(existing: dict[str, str]) -> dict[str, str]:
    """Configure OpenAI API embedding provider."""
    config: dict[str, str] = {}

    existing_key = existing.get("OPENMEM_EMBEDDING_API_KEY", "")
    if existing_key:
        api_key = _ask_secret("OpenAI API key", default=existing_key)
    else:
        api_key = _ask_secret("OpenAI API key")

    if not api_key:
        print("    API key is required for OpenAI.")
        return {}

    model = _ask(
        "Embedding model",
        default=existing.get("OPENMEM_EMBEDDING_MODEL", "text-embedding-3-small"),
    )

    dims_str = _ask(
        "Dimensions (leave blank for model default)",
        default=existing.get("OPENMEM_EMBEDDING_DIMENSIONS", ""),
    )
    dimensions = int(dims_str) if dims_str else None

    print("\n    Validating connection...")
    ok, msg = _validate_openai_embedding(
        api_key=api_key,
        base_url="https://api.openai.com/v1",
        model=model,
        dimensions=dimensions,
    )
    if ok:
        print(f"    {msg}")
    else:
        print(f"    {msg}")
        if not _ask_confirm("Save anyway?", default=False):
            return {}

    config["OPENMEM_EMBEDDING_PROVIDER"] = "openai"
    config["OPENMEM_EMBEDDING_API_KEY"] = api_key
    config["OPENMEM_EMBEDDING_MODEL"] = model
    config["OPENMEM_EMBEDDING_BASE_URL"] = "https://api.openai.com/v1"
    if dimensions is not None:
        config["OPENMEM_EMBEDDING_DIMENSIONS"] = str(dimensions)

    return config


def _setup_ollama(existing: dict[str, str]) -> dict[str, str]:
    """Configure Ollama (local) embedding provider."""
    config: dict[str, str] = {}

    base = _ask(
        "Ollama URL",
        default=existing.get("OPENMEM_EMBEDDING_BASE_URL", "http://localhost:11434").replace("/v1", ""),
    ).rstrip("/")

    model = _ask(
        "Model name",
        default=existing.get("OPENMEM_EMBEDDING_MODEL", "nomic-embed-text"),
    )

    # Test Ollama connectivity
    print("\n    Checking Ollama...")
    ok, msg = _validate_ollama(base)
    if not ok:
        print(f"    {msg}")
        if not _ask_confirm("Save anyway?", default=False):
            return {}
    else:
        print(f"    {msg}")

        # Test the embedding endpoint
        print("    Testing embedding model...")
        ok2, msg2 = _validate_openai_embedding(
            api_key="ollama",
            base_url=f"{base}/v1",
            model=model,
        )
        if ok2:
            print(f"    {msg2}")
        else:
            print(f"    {msg2}")
            if not _ask_confirm("Save anyway?", default=False):
                return {}

    config["OPENMEM_EMBEDDING_PROVIDER"] = "openai"
    config["OPENMEM_EMBEDDING_API_KEY"] = "ollama"
    config["OPENMEM_EMBEDDING_MODEL"] = model
    config["OPENMEM_EMBEDDING_BASE_URL"] = f"{base}/v1"

    return config


def _setup_custom(existing: dict[str, str]) -> dict[str, str]:
    """Configure a custom OpenAI-compatible embedding endpoint."""
    config: dict[str, str] = {}

    base_url = _ask(
        "Base URL (OpenAI-compatible)",
        default=existing.get("OPENMEM_EMBEDDING_BASE_URL", ""),
    )
    if not base_url:
        print("    Base URL is required.")
        return {}

    model = _ask(
        "Model name",
        default=existing.get("OPENMEM_EMBEDDING_MODEL", ""),
    )
    if not model:
        print("    Model name is required.")
        return {}

    existing_key = existing.get("OPENMEM_EMBEDDING_API_KEY", "")
    api_key = _ask_secret(
        "API key (leave blank if none)",
        default=existing_key,
    )

    dims_str = _ask(
        "Dimensions (leave blank for model default)",
        default=existing.get("OPENMEM_EMBEDDING_DIMENSIONS", ""),
    )
    dimensions = int(dims_str) if dims_str else None

    print("\n    Validating connection...")
    ok, msg = _validate_openai_embedding(
        api_key=api_key or "none",
        base_url=base_url,
        model=model,
        dimensions=dimensions,
    )
    if ok:
        print(f"    {msg}")
    else:
        print(f"    {msg}")
        if not _ask_confirm("Save anyway?", default=False):
            return {}

    config["OPENMEM_EMBEDDING_PROVIDER"] = "openai"
    config["OPENMEM_EMBEDDING_MODEL"] = model
    config["OPENMEM_EMBEDDING_BASE_URL"] = base_url
    if api_key:
        config["OPENMEM_EMBEDDING_API_KEY"] = api_key
    if dimensions is not None:
        config["OPENMEM_EMBEDDING_DIMENSIONS"] = str(dimensions)

    return config


def _setup_none() -> dict[str, str]:
    """Configure keyword-only search (no embeddings)."""
    print("\n    Semantic search will be disabled.")
    print("    Only FTS5 keyword matching will be available.")
    if not _ask_confirm("Continue?", default=True):
        return {}
    return {"OPENMEM_EMBEDDING_PROVIDER": "none"}


# --- Main ---


def main() -> None:
    """Run the interactive setup wizard."""
    try:
        _run_wizard()
    except KeyboardInterrupt:
        print("\n\n  Setup cancelled.")
        sys.exit(1)


def _run_wizard() -> None:
    """Main wizard flow."""
    print()
    print("  OpenMem Setup")
    print("  =============")
    print()

    existing = _load_existing_config()
    if existing:
        print(f"  Found existing config at {CONFIG_FILE}")
        print("  Current values will be shown as defaults.")
        print()

    # Step 1: Storage path
    storage_path = _ask(
        "Storage path",
        default=existing.get("OPENMEM_STORAGE_PATH", "~/.openmem/memory.db"),
    )

    # Ensure parent directory exists
    expanded = Path(storage_path).expanduser()
    expanded.parent.mkdir(parents=True, exist_ok=True)

    # Step 2: Embedding provider
    choice = _ask_choice(
        "Embedding provider:",
        [
            "OpenAI API",
            "Local (Ollama)",
            "Custom OpenAI-compatible endpoint",
            "None (keyword search only)",
        ],
        default=1,
    )

    if choice == 1:
        embedding_config = _setup_openai(existing)
    elif choice == 2:
        embedding_config = _setup_ollama(existing)
    elif choice == 3:
        embedding_config = _setup_custom(existing)
    else:
        embedding_config = _setup_none()

    if not embedding_config:
        print("\n  Setup cancelled.")
        return

    # Build final config
    config = {"OPENMEM_STORAGE_PATH": storage_path}
    config.update(embedding_config)

    # Check for existing file
    if CONFIG_FILE.exists() and existing:
        if not _ask_confirm(f"\n  Overwrite {CONFIG_FILE}?", default=True):
            print("  Setup cancelled.")
            return

    # Save
    path = _save_config(config)

    # Summary
    print()
    print("  Setup complete!")
    print(f"  Config saved to: {path}")
    print()
    print("  Configuration:")
    for key, value in config.items():
        display = _mask_key(value) if "KEY" in key else value
        print(f"    {key}={display}")

    print()
    print("  Next steps:")
    print("    Start the MCP server:  openmem-mcp")
    print()
    print("    Or add to Claude Desktop (claude_desktop_config.json):")
    print('    {')
    print('      "mcpServers": {')
    print('        "openmem": {')
    print('          "command": "openmem-mcp"')
    print('        }')
    print('      }')
    print('    }')
    print()


if __name__ == "__main__":
    main()
